sudo: required
dist: trusty
language: python

os:
    - linux
    - osx

osx_image: xcode8

python:
    - 3.6

before_install:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then travis_retry brew install gcc; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo apt-get update -q; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo apt-get install gcc-7 g++-7 -y; fi
    - export CC=gcc-7 && export CXX=g++-7
    - echo $CC
    - echo $CXX
    - $CC --version
    - $CXX --version
    - python --version
    - travis_retry pip install -r requirements.txt

install:
    - cp setup.cfg.example setup.cfg
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sed -i '' 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

before_script:
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sleep 3; fi # give xvfb some time to start
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then glxinfo || true; fi

script:
    - python setup.py test

notifications:
    email: false
    slack:
      rooms:
        - secure: "neuHuwQthASkc0MRU9M5JxaSfUM6Ckk2O1dkROVJZY7xzoJbdwVLV2quYqkCGmCJqSUfR5GGnBBYSGLOUyTas8hXcncC8nafr2NiBLKxQ+ylTt5CAXLOnSQNtVOR+pmaHzLGOSU89EGMQIFzKw5C2DDAXg1bXgXBCnpjy9E6dtkfio+CpNRbRtRibXRvtLXDqdmEY2/4UxIEM7Z9AjCzJT77YEY73wLjO3Khxu3Q/YDqWC7zNYT5lHJKyc0Tc0WJ99yjVJeWiXDxHImA7b10qsG7uqiyqQO0BsDYCm+pku+/aC5CP4tRfc4FGgR3eoi//oz74aTXIyKLAJ9qJxIbuRobGtYEW3T4mdn4kVqyoHG5f+OFnUYbj9Ruz+TWoCmzyv8Wvz1ZV+2ed0Iq9o5HSn6m7C4D9p1wVgUHgQKALow8RjnOBpSNy2MwfsKYM+XVwFm/ptPKpjSSw4bdExP3XXnZKyuUa1zmUEQtqVrWCYO3oN4PaL6067osP5YuhztGHcy9Z0XhhTLMlObFXYyYSqAEklHS42+ldlRJr2N1Smrd4ba0X+XLfb4a+DmdndncxujyYopMwlMdGTZeUZLJ+nWa4M7f5LbcU8oB0YTeDsovKktm6IZXQXXsQZdz9eFTCMolvUel9vzolK5BkuigNW/cZR3tfOdAeXBpsuYBBCQ="
