sudo: required
dist: trusty
language: generic

# run on linux and mac
os:
    - linux
    - osx

# different builds
env:
    - VTK=6 PYTHON=2
    - VTK=7 PYTHON=2
    # - VTK=7 PYTHON=3

before_install:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
        export CC=gcc;
        export CXX=g++;
      else
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt-get update -q;
        sudo apt-get install gcc-6 g++-6 -y;
        export CC=gcc-6;
        export CXX=g++-6;
      fi
    - scripts/install_conda.sh -e atoman -p $PYTHON -V $VTK -d $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - source activate atoman
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then conda install -q gcc; fi
    - echo $CC
    - echo $CXX
    - $CC --version
    - $CXX --version
    - python --version

install:
    - cp setup.cfg.example setup.cfg
#    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then sed -i '' 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

before_script:
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sleep 3; fi # give xvfb some time to start

script:
    - python setup.py test
