sudo: required
dist: trusty
language: generic

matrix:
    include:
        - os: osx
          osx_image: xcode9.3
          env: PYTHON_VERSION=2.7
        - os: osx
          osx_image: xcode9.3
          env: PYTHON_VERSION=3.6
        - os: linux
          env: PYTHON_VERSION=2.7
        - os: linux
          env: PYTHON_VERSION=3.6

before_install:
    - export OMP_NUM_THREADS=4
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo apt-get update -q; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then travis_retry sudo apt-get install gcc-7 g++-7 -y; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export CC=gcc-7 && export CXX=g++-7; fi
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export CONDA_OS=MacOSX; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export CONDA_OS=Linux; fi
    - travis_retry curl -L -o /tmp/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS}-x86_64.sh
    - bash /tmp/miniconda.sh -b -p ${HOME}/miniconda
    - source ${HOME}/miniconda/etc/profile.d/conda.sh
    - travis_retry conda create -y -q -n atoman python=${PYTHON_VERSION} pip
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then conda install -y -q -n atoman gcc; fi
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export CC=gcc && export CXX=g++; fi
    - conda activate atoman
    - $CC --version
    - $CXX --version
    - python --version
    - if [ "${PYTHON_VERSION}" == "2.7" ]; then pip install numpy scipy matplotlib vtk pillow nose setuptools sphinx sphinx_rtd_theme paramiko pyhull pyinstaller; fi
    - if [ "${PYTHON_VERSION}" == "2.7" ]; then conda install -y -q -n atoman pyqt; fi
    - if [ "${PYTHON_VERSION}" != "2.7" ]; then pip install -r requirements.txt; fi

install:
    - cp setup.cfg.example setup.cfg
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sed -i '' 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

script:
    - python setup.py test

notifications:
    email: false
    slack:
      rooms:
        - secure: "neuHuwQthASkc0MRU9M5JxaSfUM6Ckk2O1dkROVJZY7xzoJbdwVLV2quYqkCGmCJqSUfR5GGnBBYSGLOUyTas8hXcncC8nafr2NiBLKxQ+ylTt5CAXLOnSQNtVOR+pmaHzLGOSU89EGMQIFzKw5C2DDAXg1bXgXBCnpjy9E6dtkfio+CpNRbRtRibXRvtLXDqdmEY2/4UxIEM7Z9AjCzJT77YEY73wLjO3Khxu3Q/YDqWC7zNYT5lHJKyc0Tc0WJ99yjVJeWiXDxHImA7b10qsG7uqiyqQO0BsDYCm+pku+/aC5CP4tRfc4FGgR3eoi//oz74aTXIyKLAJ9qJxIbuRobGtYEW3T4mdn4kVqyoHG5f+OFnUYbj9Ruz+TWoCmzyv8Wvz1ZV+2ed0Iq9o5HSn6m7C4D9p1wVgUHgQKALow8RjnOBpSNy2MwfsKYM+XVwFm/ptPKpjSSw4bdExP3XXnZKyuUa1zmUEQtqVrWCYO3oN4PaL6067osP5YuhztGHcy9Z0XhhTLMlObFXYyYSqAEklHS42+ldlRJr2N1Smrd4ba0X+XLfb4a+DmdndncxujyYopMwlMdGTZeUZLJ+nWa4M7f5LbcU8oB0YTeDsovKktm6IZXQXXsQZdz9eFTCMolvUel9vzolK5BkuigNW/cZR3tfOdAeXBpsuYBBCQ="
