sudo: false
language: generic

# install recent GCC
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        
        packages:
            - gcc-6
            - g++-6

# run on linux and mac
os:
    - linux
    - osx

# different builds
env:
    - VTK=5 PYTHON=2
    - VTK=6 PYTHON=2
    - VTK=7 PYTHON=2
    # - VTK=7 PYTHON=3

before_install:
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update; brew outdated gcc || brew upgrade gcc; fi
    - scripts/install_conda.sh -e atoman -p $PYTHON -V $VTK -d $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - source activate atoman
    - export CC=gcc
    - export CXX=g++

install:
    - echo $CC
    - echo $CXX
    - $CC --version
    - $CXX --version
    - python --version
    - cp setup.cfg.example setup.cfg
    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then sed -i '' 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

script:
    - python setup.py test
