sudo: false
language: generic

# install recent GCC
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        
        packages:
            - gcc-6
            - g++-6

# run on linux and mac
os:
    - linux
    - osx

# different builds
env:
#    - VTK=5 PYTHON=2
    - VTK=6 PYTHON=2
    - VTK=7 PYTHON=2
    # - VTK=7 PYTHON=3

before_install:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
        brew update;
        brew upgrade;
        brew install gcc6;
        export CC=gcc-6;
        export CXX=g++-6;
      else
        export CC=gcc;
        export CXX=g++;
      fi
    - which gcc-6 || true
    - $CC --version
    - $CXX --version
    - scripts/install_conda.sh -e atoman -p $PYTHON -V $VTK -d $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - source activate atoman

install:
    - python --version
    - cp setup.cfg.example setup.cfg
#    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then sed -i '' 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

before_script:
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sleep 3; fi # give xvfb some time to start

script:
    - python setup.py test
