"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../src/CDJSVis.py']
DATA_FILES = ["../src/data/atoms.IN",]
OPTIONS = {'argv_emulation': False,
           'iconfile': "../src/icons/CDJSVis.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
